### ISSUE TITLE
Where is the code for "Event Structure Pre-training"

### ISSUE THREAD

**Issue by cklsoft** [THU-KEG/CLEVE#7]
Hi, I didn't find the code about _Event Structure Pre-training_. Is it missing ?

**Comment by wzq016** [comment]
Just as the paper mentioned, we use [GCC](https://github.com/THUDM/GCC)'s code to pre-train event structures. Basically, we just change inputs to AMR graphs and run this code.

Since I am busy recently, I will try to merge this code into our pipeline when I have time later.

**Comment by liutaonuist** [comment]
> 

hello，have you realize the code of Event Structure Pre-training.？

**Comment by wzq016** [comment]
Repo updated
