### ISSUE TITLE
Event Structure Pre-training

### ISSUE THREAD

**Issue by timelosss** [THU-KEG/CLEVE#8]
请问对于amr图的编码工作代码是如何进行的？使用GCC应当如何调整输入？作者，这部分的代码可以发布一下吗？

**Comment by liutaonuist** [comment]
同问。，，，

**Comment by liutaonuist** [comment]
> 请问对于amr图的编码工作代码是如何进行的？使用GCC应当如何调整输入？作者，这部分的代码可以发布一下吗？

请问事件结构模块的预训练是否已经成功实现？

**Comment by wzq016** [comment]
感谢关注，repo已更新
